# Generated by Django 3.2.13 on 2022-05-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20220504_1720'),
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='Employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employees'),
        ),
    ]
